# Laravel API Deployment Script
# This script helps deploy your Laravel API to various cloud platforms

echo "🚀 Laravel API Deployment Script"
echo "================================="
echo ""
echo "Your Dockerfile and configuration files are ready!"
echo ""
echo "📋 Deployment Options:"
echo ""
echo "1. 🚄 RAILWAY (Recommended - Easiest)"
echo "   - Install Railway CLI: npm install -g @railway/cli"
echo "   - Login: railway login"
echo "   - Deploy: railway up"
echo "   - Your API will be available at: https://your-app.railway.app"
echo ""
echo "2. 🎨 RENDER (Alternative)"
echo "   - Go to: https://render.com"
echo "   - Connect your GitHub repository"
echo "   - Create new Web Service"
echo "   - Use the render.yaml configuration"
echo "   - Your API will be available at: https://your-app.onrender.com"
echo ""
echo "3. ☁️  GOOGLE CLOUD RUN (Advanced)"
echo "   - Install Google Cloud SDK"
echo "   - Build: docker build -t gcr.io/YOUR-PROJECT/laravel-api ."
echo "   - Push: docker push gcr.io/YOUR-PROJECT/laravel-api"
echo "   - Deploy: gcloud run deploy --image gcr.io/YOUR-PROJECT/laravel-api"
echo ""
echo "📝 Next Steps:"
echo "1. Choose your preferred platform above"
echo "2. Follow the deployment instructions"
echo "3. Your API will be live with a public URL"
echo "4. Test the health endpoint: https://your-domain/api/health"
echo ""
echo "🔧 Configuration Files Created:"
echo "- Dockerfile (Optimized for Laravel)"
echo "- render.yaml (Render configuration)"
echo "- railway.yaml (Railway configuration)"
echo "- .dockerignore (Optimized build)"
echo ""
echo "✅ Your Laravel API is ready for deployment!"

# Keep the terminal open
read -p "Press Enter to continue..."